<?php $this->headTitle('Contact'); ?>

<div class="jumbotron">
    <h1>Contact</h1>
</div>

<?php if ($this->valid_submit): ?>
    <div class="alert alert-success" id="notification" role="alert"
        >Your submission has been received. Thank you for your time.</div>
<?php endif; ?>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 well" id="login-div">
        <?php
        $form = $this->form;
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <div class="form-group">
                <?php
                $element = $form->get('name');
                echo $this->formLabel($element);
                echo $this->formText($element);
                echo $this->formElementErrors($element);
                ?>
            </div>
            <div class="form-group">
                <?php
                $element = $form->get('email');
                echo $this->formLabel($element);
                echo $this->formEmail($element);
                echo $this->formElementErrors($element);
                ?>
            </div>
            <div class="form-group">
                <?php
                $element = $form->get('message');
                echo $this->formLabel($element);
                echo $this->formTextArea($element);
                echo $this->formElementErrors($element);
                ?>
            </div>
            <div class="form-group">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
